name: Change Shell
run-name: Test Change Shell
on: push
jobs:
  display-value:
    runs-on: ubuntu-latest
    steps:
      - name: Use Bash
        shell: bash
        run: echo "$SHELL"
      - name: Use Python
        shell: python
        run: |
          import os
          print(os.environ['PATH'])