name: Debug Log
run-name: Debug Log Workflow
on: push
jobs:
  debug-log:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - name: Print Debug Log
        run: echo "::debug::This is a debug log"
