name: Injection test
run-name: Injection (sanitized test)
on: pull_request
jobs:
  inject:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - run: echo "${PR_TITLE}"
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
