name: Job Summary
run-name: Job Summary Workflow
on: push
jobs:
  summarize:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - run: |
          {
            echo "## Example Title :rocket:"
            echo "- first line"
            echo "- second line"
          } >> "$GITHUB_STEP_SUMMARY"
