name: Job Summary
run-name: Job Summary Workflow
on: push
jobs:
  summarize:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "## Example Title :rocket:" >> "$GITHUB_STEP_SUMMARY"
          echo "- first line" >> "$GITHUB_STEP_SUMMARY"
          echo "- second line" >> "$GITHUB_STEP_SUMMARY"