name: Logging 02
run-name: Logging Workflow
on: push
jobs:
  logging:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - name: Logging
        run: |
          echo "::group::Show envs"
          printenv
          echo "::endgroup::"
