name: Logging 03
run-name: Logging Workflow 03
on: push
jobs:
  logging:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    env:
      PASSWORD: abcd12345
      PASSWORD_02: efgh56789
    steps:
      - name: Mask env
        run: echo "::add-mask::$PASSWORD"
      - name: Print env 01
        run: echo "$PASSWORD"
      - name: Print env 02
        run: echo "$PASSWORD_02"
