name: Matrix Workflow
run-name: Matrix Workflow
on: push
jobs:
  print-job:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - name: Print Runner OS
        run: echo "$RUNNER_OS"
        shell: bash
