name: Variables Secrets Env
run-name: Print Variables and Secrets
on:
  workflow_dispatch:
    inputs:
      environment-name:
        type: environment
        default: test
        required: false
        description: Environment name
jobs:
  print-vars-secrets:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-name }}
    steps:
      - run: echo "$USERNAME"
      - run: echo "$PASSWORD"
    env:
      USERNAME: ${{ vars.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
