name: Workflow beyond step
run-name: beyond step
on: push
jobs:
  beyond-step:
    runs-on: ubuntu-latest
    steps:
      - id: source
        run: echo "result=hello" >> "$GITHUB_OUTPUT"
      - run: echo "$RESULT"
        env:
          RESULT: ${{ steps.source.outputs.result }}
      
