name: Env default values
on: push
jobs:
  view-values:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ GITHUB_SHA }}"
      - run: echo "${{ RUNNER_OS }}"
      - run: echo "${{ GITHUB_RUN_ID }}"
