name: Workflow naming 02
on: push
run-name: Push to ${{ github.ref_name }} branch
jobs:
  naming02:
    name: naming Job 02
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello"
      - name: Check github context
        run: echo "$CONTEXT"
        env:
          CONTEXT: ${{ toJSON(github) }}
