name: Env value
on: push
jobs:
  env-job:
    runs-on: ubuntu-latest
    env:
      BRANCH: main
    steps:
      - run: echo "abc"
      - run: echo "${{ env.BRANCH }}"
      - run: date
      - uses: actions/checkout@v6
        with:
          ref: ${{ env.BRANCH }}
