name: Env value
on: push
env:
  API_BASE: http://localhost:8000
  CLIENT_ID: client_a

jobs:
  fe:
    env:
      CLIENT_ID: client_b
    runs-on: ubuntu-latest
    steps:
      - run: echo "$API_BASE"
      - run: echo "$CLIENT_ID"
