name: workflow scheduler
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  regular-job:
    runs-on: ubuntu-latest
    steps:
      - run: sudo timedatectl set-timezone Asia/Tokyo
      - run: date
      - run: echo 'scheduled job!!'
