name: Variables And Secrets
on: push
env:
  USERNAME: ${{ vars.USERNAME }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
jobs:
  embed02:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$USERNAME"
      - run: echo "$CLIENT_SECRET"
      - run: echo "$CLIENT_SECRET:0:1 $CLIENT_SECRET#?"
