name: Workflow beyond step 02
on: push
run-name: beyond step 02
jobs:
  beyond-step:
    runs-on: ubuntu-latest
    steps:
      - id: step01
        run: echo "result=Hello" >> "$GITHUB_OUTPUT"
      - run: echo "$RESULT"
        env:
          RESULT: ${{ steps.step01.outputs.result }}
